### PR TITLE
docs(installation guide): move k8s section one level up

### PR DESCRIPTION
**Pull request by meln1k**
# Description

Move the k8s installation page one level up.

# To-Dos

- [x] Format with `yarn format`
- [x] Lint with `yarn lint`
- [ ] Build successfully with `yarn build`

# Code of Conduct

By submitting this pull request, I agree to follow the [code of conduct](https://resoto.com/code-of-conduct).

### CODE REVIEW

**Comment by TheCatLady** [comment]
What is the rationale behind these changes?

**Comment by aquamatthias** [comment]
> What is the rationale behind these changes?

@TheCatLady To put k8s as "non local" installation - k8s is an option for all major cloud providers out of the box.
@meln1k I only see the change for edge, but not for the latest release - any reason for this?

**Comment by aquamatthias** [comment]
> > @TheCatLady To put k8s as "non local" installation - k8s is an option for all major cloud providers out of the box.
> 
> While this is true, we don't have provider-specific instructions. Also, isn't this confusing? To deploy with k8s to AWS, shouldn't we direct users to the AWS CDK instructions?

A lot of companies already operate a k8s cluster.
CDK is only there to setup EKS and then install resoto - so no this is not confusing.

> Technically, any of the "local" install options can be deployed to a cloud provider.

No - there is no option to deploy a docker compose stack, but there are options to deploy a  helm chart.

> "Local" isn't a perfect descriptor here so maybe the better solution is to change that wording. 🤔

Pip and docker is good for people to try it out on a local machine.  Not sure what would be a better wording?

**Comment by TheCatLady** [comment]
> No - there is no option to deploy a docker compose stack, but there are options to deploy a  helm chart.

https://docs.docker.com/cloud/ecs-integration/
 
> Pip and docker is good for people to try it out on a local machine.  Not sure what would be a better wording?

I guess what these three options really are, are "provider-agnostic" in that they aren't specific to any single cloud provider and can even be used locally.

**Comment by aquamatthias** [comment]
> Sure, but the fact remains that Docker and Kubernetes are "like" items that should be grouped together. 🤔

I tried to explain why I think k8s should belong on the same level as AWS.
I agree that docker compose theoretically can be used as a deployment target - I do not see a practical use case other than the local computer.

**Comment by TheCatLady** [comment]
> I tried to explain why I think k8s should belong on the same level as AWS. I agree that docker compose theoretically can be used as a deployment target - I do not see a practical use case other than the local computer.

What if we ungroup these install options instead of grouping them as "local installation" options? I understand where you're coming from, but my original intent was only to "highlight" the AWS option by moving these other options into another category rather than defining/limiting the scope of these options.

**Comment by TheCatLady** [comment]
Fixed in #421

**Pull request closed without merging**
