### PR TITLE
fix(docs): update helm instructions

### PR DESCRIPTION
**Pull request by kushthedude**

### CODE REVIEW

**Comment by kushthedude** [comment]
Oh we are maintaining multi-version documentations now 👌

**Review by aquamatthias — COMMENTED** [review]
Thanks. Looks good to me. Please also update the edge docs as suggested by @TheCatLady . Once this is done it can be merged.

**Comment by aquamatthias** [comment]
@kushthedude I realized, that the default resoto-values.yaml still documents `resotocore.graphdb.server`.
I think that default setting is no longer necessary, or?

**Comment by aquamatthias** [comment]
Superseded by #481

**Pull request closed without merging**
